---
- name: Install Docker and Docker compose and run containers in the server
  hosts: tag_Name_dev_server
  gather_facts: no
  become: yes

  tasks:
    - name: Install Docker on AWS Linux server  
      yum:
        update_cache: yes
        name: docker
        state: present
    - name: start the docker service
      service: 
        name: docker
        state: started
        enabled: yes

- name: install docker-compose in the server
  hosts: tag_Name_dev_server
  gather_facts: no
  
  tasks: 
    - name: create docker-compose directory
      file:
        path: ~/.docker/cli-plugins
        state: directory
    - name: chek the archicture of the server
      shell: uname -m
      register: arch_check
    - name: download the docker-compose 
      get_url: 
        url: "https://github.com/docker/compose/releases/download/v5.0.0/docker-compose-linux-{{ arch_check.stdout }}"
        dest: ~/.docker/cli-plugins/docker-compose
        mode: +x
        
- name: add docker group to ec2-user
  hosts: tag_Name_dev_server
  gather_facts: no
  become: yes

  tasks:
    - name: adding docker groupt to user
      user:
        name: ec2-user
        groups: docker
        append: yes
    - name: re-connect to the server
      meta: reset_connection

- name: pull the radis image
  hosts: tag_Name_dev_server
  gather_facts: no

  tasks: 
    - name: pull an image
      docker_image:
        name: redis
        source: pull
- name: copy docker compose file from local to server
  hosts: tag_Name_dev_server
  gather_facts: no

  tasks:
    - name: copying the docker compose file to server
      copy:
        src: /Users/eswarkumar/ansible/bootcamp-java-mysql-project/docker-compose-full.yaml
        dest: ~/docker-compose.yaml

- name: run the docker image
  hosts: tag_Name_dev_server
  gather_facts: no
  vars_files:
    - node-vars.yml
  tasks:
    - name: pulling the image from the repo
      docker_login:
        username: eswar1241
        password: "{{password}}"
    - name: run the docker compose to pull the image
      community.docker.docker_compose_v2:
        project_src: /home/ec2-user
    



        
  
        