---
- name: Deploy and configure Nexus
  hosts: droplets
  become: yes
  gather_facts: no

  tasks:
    # -----------------------
    # Install prerequisites
    # -----------------------
    - name: Update apt repo cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Java 8 and net-tools
      apt:
        pkg:
          - openjdk-8-jre-headless
          - net-tools

    # -----------------------
    # Download Nexus only if file does not exist
    # -----------------------
    - name: Check if tar already exists
      stat:
        path: /opt/nexus*.tar.gz
      register: tar_file

    - name: Download the nexus installer
      get_url:
        url: https://download.sonatype.com/nexus/3/nexus-3.86.2-01-linux-x86_64.tar.gz
        dest: /opt/nexus.tar.gz
      when: not tar_file.stat.exists

    - name: unarchive the nexus installer in server
      unarchive:
        src: /opt/nexus.tar.gz
        dest: /opt
        remote_src: yes
        creates: /opt/nexus

    - name: check if /opt/nexus alredy exists
      stat:
        path: /opt/nexus
      register: nexus_dir

    - name: find the nexus-3.86.2-01 directory
      find:
        path: /opt
        pattern: "nexus*"
        file_type: directory
      register: find_result
      when: not nexus_dir.stat.exists

    - name: rename the nexus directory
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not nexus_dir.stat.exists

    - name: removing the nexus.tar.gz file
      file:
        path: /opt/nexus.tar.gz
        state: absent
- name: create nexus user and group for to execute nexus related works
  hosts: droplets
  gather_facts: no
  become: yes

  tasks:
    - name: create nexus group
      group: 
        name: nexus
        state: present
    - name: create nexus user
      user:
        name: nexus
        group: nexus
    - name: change the ownership of nexus
      file: 
        path: /opt/nexus
        owner: nexus
        group: nexus
        state: directory
        recurse: yes
    - name: change the ownership of sonatype-work
      file: 
        path: /opt/sonatype-work
        owner: nexus
        group: nexus
        state: directory
        recurse: yes
  
- name: start nexus with nexus user
  hosts: droplets
  gather_facts: no
  become_user: nexus
  become: yes

  tasks:
    - name: Create nexus.rc file if missing
      file:
        path: /opt/nexus/bin/nexus.rc
        state: touch
        owner: nexus
        group: nexus
        mode: '0644'
    - name: Set run_as_user in nexus.rc
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^run_as_user='
        line: 'run_as_user="nexus"'
    - name: Start nexus
      command: /opt/nexus/bin/nexus start
- name: Verify nexus running
  hosts: droplets
  gather_facts: no
  tasks:
    - name: Check with ps
      shell: ps aux |grep nexus |grep -v root
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
    - name: Wait one minute
      pause:
        minutes: 1
    - name: Check with netstat
      shell: netstat -plnt
      register: app_status
    - debug: msg={{app_status.stdout_lines}}

      